jwt:
  secretKey: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refreshKey: sBub22lROtSMG4tL7Z1WwCZYvA32K2Nuk4H7qpxH18c=hjg7

spring:
  datasource:
    url: jdbc:mariadb://175.114.130.17:3306/FINAL
    username: sungq
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    username: doctorpick
    password: a13579!@#

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.example.dao

logging:
  level:
    org.springframework: DEBUG